baseURL = "https://ameenmahmood.github.io/FF"
title = "Shenantasy Fantasy Football"
copyright = "Ameen Mahmood"
pagination.pagerSize = 3 # for demonstration of pagination
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"
enableGitInfo = true

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
