# SEO keywords and description for your site.
keywords = "football"
subtitle = "Ameen Mahmood"
favicon = "https://raw.githubusercontent.com/ameenmahmood/FF/refs/heads/main/static/52735americanfootball_109430.ico"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

jsonLD = true

showAuthor = true

[author]
  name = "Ameen Mahmood"
  email = "ameenbmahmood@gmail.com"

[header]
  logo = "https://raw.githubusercontent.com/ameenmahmood/FF/refs/heads/main/static/52735americanfootball_109430.ico"
  title = "Shenantsay Fantasy Football"

[footer]
  since = 2025
  poweredby = true

[pwa]
  enabled = true
  icon = "https://raw.githubusercontent.com/ameenmahmood/FF/refs/heads/main/static/52735americanfootball_109430.ico" # should be in assets
  icon_sizes = [192, 512]

  [manifest]
  description = "Keeping up with all the drama"
